version: '3.8'

services:
  app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - svc
    environment:
      - API_URL=http://svc:8080/api
    networks:
      - internal

  svc:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - internal

networks:
  internal:
